# Generated by Django 3.0.5 on 2020-05-23 05:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Yoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(default='default.jpg', upload_to='yoga')),
                ('level', models.IntegerField(choices=[(1, 'Junior'), (2, 'Middle'), (3, 'Senior')])),
                ('title', models.CharField(default='shushi', max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('seat', 'seat'), ('mountain', 'mountain'), ('standing_start', 'standing_start'), ('treebywind', 'treebywind'), ('walking_stick', 'walking_stick'), ('buttocks', 'buttocks'), ('crocodile', 'crocodile'), ('door', 'door'), ('down_dog', 'down_dog'), ('forward_bending', 'forward_bending'), ('grinding', 'grinding'), ('half_moon3', 'half_moon3'), ('low_bow_stance', 'low_bow_stance'), ('shushi', 'shushi'), ('half_moon1', 'half_moon1'), ('half_mooon2', 'half_mooon2'), ('boat', 'boat'), ('dance', 'dance'), ('desk', 'desk'), ('monkey', 'monkey'), ('single_bridge', 'single_bridge'), ('up_dog', 'up_dog'), ('upside_angle.jpg', 'upside_angle.jpg'), ('Vbalance', 'Vbalance'), ('warrior_back', 'warrior_back'), ('wheel', 'wheel')], max_length=150)),
                ('image', models.ImageField(default='', upload_to='upload_pics')),
                ('date_published', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DownYoga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='default.jpg', upload_to='reback')),
                ('jsonFile', models.FileField(default='', upload_to='file')),
                ('content', models.TextField(default='perfect posture!', max_length=1024)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('upPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
            ],
        ),
    ]
